"""remove_birthdate_from_users

Revision ID: 140d0bae6f88
Revises: 20e21bf8e1d7
Create Date: 2025-08-06 20:18:06.165521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140d0bae6f88'
down_revision: Union[str, Sequence[str], None] = '20e21bf8e1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthdate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthdate', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
