"""Update schema to use UUIDs for user IDs

Revision ID: 20315c2aac43
Revises: d7d26d3652a6
Create Date: 2025-07-31 06:27:52.688834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20315c2aac43'
down_revision: Union[str, Sequence[str], None] = 'd7d26d3652a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraint first
    op.drop_constraint('checklists_user_id_fkey', 'checklists', type_='foreignkey')
    
    # Change column types
    op.alter_column('checklists', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    
    # Recreate foreign key constraint
    op.create_foreign_key('checklists_user_id_fkey', 'checklists', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraint
    op.drop_constraint('checklists_user_id_fkey', 'checklists', type_='foreignkey')
    
    # Revert column types
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('checklists', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    
    # Recreate foreign key constraint
    op.create_foreign_key('checklists_user_id_fkey', 'checklists', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
